import { getTeamLogo } from '@/lib/teamLogos';

export type TeamBranding = {
    displayName: string;
    primary: string;
    secondary: string;
    accent: string;
    headerText: string;
    logo: any | null;
};

const TEAM_BRANDING: Record<string, TeamBranding> = {
    ACU: {
        displayName: 'Abilene Christian',
        primary: '#4F2170',
        secondary: '#FFFFFF',
        accent: '#A7A9AC',
        headerText: '#FFFFFF',
        logo: null,
    },
    AIR_FORCE: {
        displayName: 'Air Force',
        primary: '#003594',
        secondary: '#B2B4B2',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    AKRON: {
        displayName: 'Akron',
        primary: '#041E42',
        secondary: '#A89968',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    ALABAMA: {
        displayName: 'Alabama',
        primary: '#9E1B32',
        secondary: '#FFFFFF',
        accent: '#828A8F',
        headerText: '#FFFFFF',
        logo: null,
    },
    ALABAMA_AM: {
        displayName: 'Alabama A&M',
        primary: '#800000',
        secondary: '#FFFFFF',
        accent: '#A89968',
        headerText: '#FFFFFF',
        logo: null,
    },
    ALBANY: {
        displayName: 'Albany',
        primary: '#46166B',
        secondary: '#EEB211',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    ALCORN_STATE: {
        displayName: 'Alcorn State',
        primary: '#512D6D',
        secondary: '#CC8A00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    AMERICAN: {
        displayName: 'American',
        primary: '#002F6C',
        secondary: '#C41130',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    APP_STATE: {
        displayName: 'Appalachian State',
        primary: '#222222',
        secondary: '#FFCC00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    ARIZONA: {
        displayName: 'Arizona',
        primary: '#003366',
        secondary: '#CC0033',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    ARIZONA_STATE: {
        displayName: 'Arizona State',
        primary: '#8C1D40',
        secondary: '#FFC627',
        accent: '#1E1E1E',
        headerText: '#FFFFFF',
        logo: null,
    },
    ARKANSAS: {
        displayName: 'Arkansas',
        primary: '#9D2235',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    ARKANSAS_STATE: {
        displayName: 'Arkansas State',
        primary: '#CC092F',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    ARMY: {
        displayName: 'Army',
        primary: '#000000',
        secondary: '#D4BF91',
        accent: '#B2B4B3',
        headerText: '#FFFFFF',
        logo: null,
    },
    AUBURN: {
        displayName: 'Auburn',
        primary: '#0C2340',
        secondary: '#E87722',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    AUSTIN_PEAY: {
        displayName: 'Austin Peay',
        primary: '#BA0C2F',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    BALL_STATE: {
        displayName: 'Ball State',
        primary: '#BA0C2F',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    BAYLOR: {
        displayName: 'Baylor',
        primary: '#154734',
        secondary: '#FFB81C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    BELLARMINE: {
        displayName: 'Bellarmine',
        primary: '#752936',
        secondary: '#C8C8C8',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    BELMONT: {
        displayName: 'Belmont',
        primary: '#001A4A',
        secondary: '#C41230',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    BETHUNECOOKMAN: {
        displayName: 'Bethune-Cookman',
        primary: '#7A0019',
        secondary: '#F2A900',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    BINGHAMTON: {
        displayName: 'Binghamton',
        primary: '#005A43',
        secondary: '#BF0D3E',
        accent: '#169B62',
        headerText: '#FFFFFF',
        logo: null,
    },
    BOISE_STATE: {
        displayName: 'Boise State',
        primary: '#0033A0',
        secondary: '#D64309',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    BOSTON: {
        displayName: 'Boston University',
        primary: '#CC0000',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    BOSTON_COLLEGE: {
        displayName: 'Boston College',
        primary: '#8C2232',
        secondary: '#B4A269',
        accent: '#B4B2B3',
        headerText: '#FFFFFF',
        logo: null,
    },
    BOWLING_GREEN: {
        displayName: 'Bowling Green',
        primary: '#FE5000',
        secondary: '#4F2C1D',
        accent: '#CDA077',
        headerText: '#FFFFFF',
        logo: null,
    },
    BRADLEY: {
        displayName: 'Bradley',
        primary: '#A50000',
        secondary: '#FFFFFF',
        accent: '#B1B3B3',
        headerText: '#FFFFFF',
        logo: null,
    },
    BROWN: {
        displayName: 'Brown',
        primary: '#4E3629',
        secondary: '#C00404',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    BRYANT: {
        displayName: 'Bryant',
        primary: '#000000',
        secondary: '#b4975b',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    BUCKNELL: {
        displayName: 'Bucknell',
        primary: '#E87722',
        secondary: '#003865',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    BUFFALO: {
        displayName: 'Buffalo',
        primary: '#005BBB',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    BUTLER: {
        displayName: 'Butler',
        primary: '#13294B',
        secondary: '#C8C9C7',
        accent: '#00A3E0',
        headerText: '#FFFFFF',
        logo: null,
    },
    BYU: {
        displayName: 'BYU',
        primary: '#002E5D',
        secondary: '#FFFFFF',
        accent: '#6CACE4',
        headerText: '#FFFFFF',
        logo: null,
    },
    C_O_CHARLESTON: {
        displayName: 'College of Charleston',
        primary: '#800000',
        secondary: '#9d8958',
        accent: '#B1B3B3',
        headerText: '#FFFFFF',
        logo: null,
    },
    CAL: {
        displayName: 'Cal',
        primary: '#003262',
        secondary: '#FDB515',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    CSUB: {
        displayName: 'CSU Bakersfield',
        primary: '#003594',
        secondary: '#FFC72C',
        accent: '#707372',
        headerText: '#FFFFFF',
        logo: null,
    },
    CSUF: {
        displayName: 'Cal State Fullerton',
        primary: '#00274C',
        secondary: '#DC8218',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    CSUN: {
        displayName: 'CSUN',
        primary: '#D22030',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    CAL_POLY: {
        displayName: 'Cal Poly',
        primary: '#003831',
        secondary: '#FFE395',
        accent: '#B38F4F',
        headerText: '#FFFFFF',
        logo: null,
    },
    CAMPBELL: {
        displayName: 'Campbell',
        primary: '#EA7125',
        secondary: '#1E252B',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    CANISIUS: {
        displayName: 'Canisius',
        primary: '#0C2340',
        secondary: '#FFBA00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    CENTRAL_MICHIGAN: {
        displayName: 'Central Michigan',
        primary: '#6A0032',
        secondary: '#FFC82E',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    CHARLOTTE: {
        displayName: 'Charlotte',
        primary: '#00703C',
        secondary: '#FFFFFF',
        accent: '#B2B4B2',
        headerText: '#FFFFFF',
        logo: null,
    },
    CHATTANOOGA: {
        displayName: 'Chattanooga',
        primary: '#00386B',
        secondary: '#E0AA0F',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    CINCINNATI: {
        displayName: 'Cincinnati',
        primary: '#E00122',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    CLEMSON: {
        displayName: 'Clemson',
        primary: '#F56600',
        secondary: '#522D80',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    CLEVELAND_STATE: {
        displayName: 'Cleveland State',
        primary: '#006747',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    COASTAL_CAROLINA: {
        displayName: 'Coastal Carolina',
        primary: '#006f71',
        secondary: '#A27752',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    COLGATE: {
        displayName: 'Colgate',
        primary: '#821019',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    COLORADO: {
        displayName: 'Colorado',
        primary: '#000000',
        secondary: '#CFB87C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    COLORADO_STATE: {
        displayName: 'Colorado State',
        primary: '#1E4D2B',
        secondary: '#C8C372',
        accent: '#59595B',
        headerText: '#FFFFFF',
        logo: null,
    },
    COPPIN_STATE: {
        displayName: 'Coppin State',
        primary: '#003366',
        secondary: '#FFCC00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    CORNELL: {
        displayName: 'Cornell',
        primary: '#B31B1B',
        secondary: '#FFFFFF',
        accent: '#221F20',
        headerText: '#FFFFFF',
        logo: null,
    },
    CREIGHTON: {
        displayName: 'Creighton',
        primary: '#005CA9',
        secondary: '#FFFFFF',
        accent: '#041E42',
        headerText: '#FFFFFF',
        logo: null,
    },
    DARTMOUTH: {
        displayName: 'Dartmouth',
        primary: '#00693E',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    DAVIDSON: {
        displayName: 'Davidson',
        primary: '#AC1A2F',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    DAYTON: {
        displayName: 'Dayton',
        primary: '#CE1141',
        secondary: '#004B8D',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    DELAWARE: {
        displayName: 'Delaware',
        primary: '#00539F',
        secondary: '#FFD200',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    DELAWARE_STATE: {
        displayName: 'Delaware State',
        primary: '#EE3124',
        secondary: '#72CDF4',
        accent: '#009DDC',
        headerText: '#FFFFFF',
        logo: null,
    },
    DENVER: {
        displayName: 'Denver',
        primary: '#8B2332',
        secondary: '#8B6F4B',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    DEPAUL: {
        displayName: 'DePaul',
        primary: '#003DA5',
        secondary: '#CE112D',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    DETROIT_MERCY: {
        displayName: 'Detroit Mercy',
        primary: '#002D72',
        secondary: '#A6093D',
        accent: '#D7D2CB',
        headerText: '#FFFFFF',
        logo: null,
    },
    DRAKE: {
        displayName: 'Drake',
        primary: '#004477',
        secondary: '#FFFFFF',
        accent: '#999999',
        headerText: '#FFFFFF',
        logo: null,
    },
    DREXEL: {
        displayName: 'Drexel',
        primary: '#00437B',
        secondary: '#FFDA02',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    DUKE: {
        displayName: 'Duke',
        primary: '#003087',
        secondary: '#FFFFFF',
        accent: '#012169',
        headerText: '#FFFFFF',
        logo: null,
    },
    DUQUESNE: {
        displayName: 'Duquesne',
        primary: '#041E42',
        secondary: '#BA0C2F',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    EKU: {
        displayName: 'Eastern Kentucky',
        primary: '#8A0039',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    ETSU: {
        displayName: 'East Tennessee State',
        primary: '#041E42',
        secondary: '#FFC72C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    EWU: {
        displayName: 'Eastern Washington',
        primary: '#A10022',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    EAST_CAROLINA: {
        displayName: 'East Carolina',
        primary: '#592A8A',
        secondary: '#FEC923',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    EASTERN_ILLINOIS: {
        displayName: 'Eastern Illinois',
        primary: '#004B83',
        secondary: '#919295',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    EASTERN_MICHIGAN: {
        displayName: 'Eastern Michigan',
        primary: '#006633',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    ELON: {
        displayName: 'Elon',
        primary: '#73000A',
        secondary: '#B59A57',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    EVANSVILLE: {
        displayName: 'Evansville',
        primary: '#52237F',
        secondary: '#F36F21',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    FAU: {
        displayName: 'Florida Atlantic',
        primary: '#003366',
        secondary: '#CC0000',
        accent: '#8A8D8F',
        headerText: '#FFFFFF',
        logo: null,
    },
    FDU: {
        displayName: 'Fairleigh Dickinson',
        primary: '#28334A',
        secondary: '#72293C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    FGCU: {
        displayName: 'Florida Gulf Coast',
        primary: '#002D72',
        secondary: '#007749',
        accent: '#B9975B',
        headerText: '#FFFFFF',
        logo: null,
    },
    FIU: {
        displayName: 'Florida International',
        primary: '#081E3F',
        secondary: '#B6862C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    FAIRFIELD: {
        displayName: 'Fairfield',
        primary: '#B31B1B',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    FLORIDA: {
        displayName: 'Florida',
        primary: '#0021A5',
        secondary: '#FA4616',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    FLORIDA_AM: {
        displayName: 'Florida A&M',
        primary: '#EE7624',
        secondary: '#1B5633',
        accent: '#231F20',
        headerText: '#FFFFFF',
        logo: null,
    },
    FLORIDA_STATE: {
        displayName: 'Florida State',
        primary: '#782F40',
        secondary: '#CEB888',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    FORDHAM: {
        displayName: 'Fordham',
        primary: '#860038',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    FRESNO_STATE: {
        displayName: 'Fresno State',
        primary: '#B1102B',
        secondary: '#13284C',
        accent: '#CED1D4',
        headerText: '#FFFFFF',
        logo: null,
    },
    FURMAN: {
        displayName: 'Furman',
        primary: '#582C83',
        secondary: '#FFFFFF',
        accent: '#201547',
        headerText: '#FFFFFF',
        logo: null,
    },
    GARDNERWEBB: {
        displayName: 'Gardner-Webb',
        primary: '#A80532',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    GEORGE_MASON: {
        displayName: 'George Mason',
        primary: '#006633',
        secondary: '#FFCC33',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    GEORGE_WASHINGTON: {
        displayName: 'George Washington',
        primary: '#00407A',
        secondary: '#A4864B',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    GEORGETOWN: {
        displayName: 'Georgetown',
        primary: '#041E42',
        secondary: '#9EA2A2',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    GEORGIA: {
        displayName: 'Georgia',
        primary: '#BA0C2F',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    GEORGIA_SOUTHERN: {
        displayName: 'Georgia Southern',
        primary: '#011E41',
        secondary: '#87714D',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    GEORGIA_STATE: {
        displayName: 'Georgia State',
        primary: '#0039A6',
        secondary: '#FFFFFF',
        accent: '#C60C30',
        headerText: '#FFFFFF',
        logo: null,
    },
    GEORGIA_TECH: {
        displayName: 'Georgia Tech',
        primary: '#003057',
        secondary: '#B3A369',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    GONZAGA: {
        displayName: 'Gonzaga',
        primary: '#041E42',
        secondary: '#C8102E',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    GRAMBLING_STATE: {
        displayName: 'Grambling State',
        primary: '#000000',
        secondary: '#EAA921',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    GRAND_CANYON: {
        displayName: 'Grand Canyon',
        primary: '#522398',
        secondary: '#000000',
        accent: '#9D9FA2',
        headerText: '#FFFFFF',
        logo: null,
    },
    HARVARD: {
        displayName: 'Harvard',
        primary: '#A41034',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    HAWAII: {
        displayName: 'Hawaii',
        primary: '#024731',
        secondary: '#C1C6C8',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    HIGH_POINT: {
        displayName: 'High Point',
        primary: '#512698',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    HOFSTRA: {
        displayName: 'Hofstra',
        primary: '#003591',
        secondary: '#FFC72C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    HOLY_CROSS: {
        displayName: 'Holy Cross',
        primary: '#602D89',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    HOUSTON: {
        displayName: 'Houston',
        primary: '#C8102E',
        secondary: '#FFFFFF',
        accent: '#231F20',
        headerText: '#FFFFFF',
        logo: null,
    },
    HOWARD: {
        displayName: 'Howard',
        primary: '#003366',
        secondary: '#E51937',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    IDAHO: {
        displayName: 'Idaho',
        primary: '#000000',
        secondary: '#F4D35E',
        accent: '#A2AAAD',
        headerText: '#FFFFFF',
        logo: null,
    },
    IDAHO_STATE: {
        displayName: 'Idaho State',
        primary: '#F47920',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    ILLINOIS: {
        displayName: 'Illinois',
        primary: '#FF5F05',
        secondary: '#13294B',
        accent: '#707372',
        headerText: '#FFFFFF',
        logo: null,
    },
    ILLINOIS_STATE: {
        displayName: 'Illinois State',
        primary: '#CE1126',
        secondary: '#F9DD16',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    INCARNATE_WORD: {
        displayName: 'Incarnate Word',
        primary: '#CC0000',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    INDIANA: {
        displayName: 'Indiana',
        primary: '#990000',
        secondary: '#EEEDEB',
        accent: '#231F20',
        headerText: '#FFFFFF',
        logo: null,
    },
    INDIANA_STATE: {
        displayName: 'Indiana State',
        primary: '#0142BC',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    IONA: {
        displayName: 'Iona',
        primary: '#71112D',
        secondary: '#F3D017',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    IOWA: {
        displayName: 'Iowa',
        primary: '#000000',
        secondary: '#FFCD00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    IOWA_STATE: {
        displayName: 'Iowa State',
        primary: '#C8102E',
        secondary: '#F1BE48',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    IPFW: {
        displayName: 'Purdue Fort Wayne',
        primary: '#000000',
        secondary: '#FFB81C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    IUPUI: {
        displayName: 'IU Indianapolis',
        primary: '#9D2235',
        secondary: '#DFD1A7',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    JACKSON_STATE: {
        displayName: 'Jackson State',
        primary: '#002147',
        secondary: '#FFFFFF',
        accent: '#C0C0C0',
        headerText: '#FFFFFF',
        logo: null,
    },
    JACKSONVILLE: {
        displayName: 'Jacksonville',
        primary: '#006747',
        secondary: '#BB991C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    JAMES_MADISON: {
        displayName: 'James Madison',
        primary: '#450084',
        secondary: '#CBB677',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    KANSAS: {
        displayName: 'Kansas',
        primary: '#0051BA',
        secondary: '#E8000D',
        accent: '#FFC82D',
        headerText: '#FFFFFF',
        logo: null,
    },
    KANSAS_STATE: {
        displayName: 'Kansas State',
        primary: '#512888',
        secondary: '#FFFFFF',
        accent: '#D1D3D4',
        headerText: '#FFFFFF',
        logo: null,
    },
    KENNESAW_STATE: {
        displayName: 'Kennesaw State',
        primary: '#000000',
        secondary: '#FFC629',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    KENT_STATE: {
        displayName: 'Kent State',
        primary: '#002664',
        secondary: '#EAAB14',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    KENTUCKY: {
        displayName: 'Kentucky',
        primary: '#0033A0',
        secondary: '#FFFFFF',
        accent: '#C4CED4',
        headerText: '#FFFFFF',
        logo: null,
    },
    LA_TECH: {
        displayName: 'Louisiana Tech',
        primary: '#002F8B',
        secondary: '#E31B23',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    LA_SALLE: {
        displayName: 'La Salle',
        primary: '#002D62',
        secondary: '#FDB927',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    LAMAR: {
        displayName: 'Lamar',
        primary: '#C0111F',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    LEHIGH: {
        displayName: 'Lehigh',
        primary: '#653600',
        secondary: '#cfab7a',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    LIBERTY: {
        displayName: 'Liberty',
        primary: '#002D62',
        secondary: '#C41230',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    LIPSCOMB: {
        displayName: 'Lipscomb',
        primary: '#331E54',
        secondary: '#F4AA00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    LITTLE_ROCK: {
        displayName: 'Little Rock',
        primary: '#6E2639',
        secondary: '#A7A9AC',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    LONG_BEACH_STATE: {
        displayName: 'Long Beach State',
        primary: '#000000',
        secondary: '#FFC72A',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    LONGWOOD: {
        displayName: 'Longwood',
        primary: '#15213B',
        secondary: '#999D9E',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    LOUISVILLE: {
        displayName: 'Louisville',
        primary: '#AD0000',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    LOYOLA_CHICAGO: {
        displayName: 'Loyola Chicago',
        primary: '#922247',
        secondary: '#FEBD18',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    LOYOLA_MARYLAND: {
        displayName: 'Loyola Maryland',
        primary: '#00694E',
        secondary: '#CACAC8',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    LOYOLA_MARYMOUNT: {
        displayName: 'Loyola Marymount',
        primary: '#B62B3A',
        secondary: '#00447C',
        accent: '#C8C9C7',
        headerText: '#FFFFFF',
        logo: null,
    },
    LSU: {
        displayName: 'LSU',
        primary: '#461D7C',
        secondary: '#FDD023',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MAINE: {
        displayName: 'Maine',
        primary: '#003263',
        secondary: '#B0D7FF',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MANHATTAN: {
        displayName: 'Manhattan',
        primary: '#00703C',
        secondary: '#FFFFFF',
        accent: '#00703C',
        headerText: '#FFFFFF',
        logo: null,
    },
    MARIST: {
        displayName: 'Marist',
        primary: '#C8102E',
        secondary: '#FFFFFF',
        accent: '#B2B2B2',
        headerText: '#FFFFFF',
        logo: null,
    },
    MARQUETTE: {
        displayName: 'Marquette',
        primary: '#003366',
        secondary: '#FFB81C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MARSHALL: {
        displayName: 'Marshall',
        primary: '#00B140',
        secondary: '#27251F',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MARYLAND: {
        displayName: 'Maryland',
        primary: '#E03A3E',
        secondary: '#FFD520',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    MCNEESE: {
        displayName: 'McNeese',
        primary: '#00529B',
        secondary: '#FFD204',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MEMPHIS: {
        displayName: 'Memphis',
        primary: '#003087',
        secondary: '#9EA2A2',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MERCER: {
        displayName: 'Mercer',
        primary: '#F76800',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MERRIMACK: {
        displayName: 'Merrimack',
        primary: '#003768',
        secondary: '#FDB813',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MIAMI: {
        displayName: 'Miami',
        primary: '#005030',
        secondary: '#F47321',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MIAMI_OH: {
        displayName: 'Miami (OH)',
        primary: '#B61E2E',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MICHIGAN: {
        displayName: 'Michigan',
        primary: '#00274C',
        secondary: '#FFCB05',
        accent: '#1D1D1D',
        headerText: '#FFFFFF',
        logo: null,
    },
    MICHIGAN_STATE: {
        displayName: 'Michigan State',
        primary: '#18453B',
        secondary: '#FFFFFF',
        accent: '#B2B4B2',
        headerText: '#FFFFFF',
        logo: null,
    },
    MIDDLE_TENNESSEE: {
        displayName: 'Middle Tennessee',
        primary: '#0066CC',
        secondary: '#000000',
        accent: '#69B3E7',
        headerText: '#FFFFFF',
        logo: null,
    },
    MINNESOTA: {
        displayName: 'Minnesota',
        primary: '#7A0019',
        secondary: '#FFCC33',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MISSISSIPPI_STATE: {
        displayName: 'Mississippi State',
        primary: '#5D1725',
        secondary: '#FFFFFF',
        accent: '#C1C6C8',
        headerText: '#FFFFFF',
        logo: null,
    },
    MISSOURI: {
        displayName: 'Missouri',
        primary: '#000000',
        secondary: '#F1B82D',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MISSOURI_STATE: {
        displayName: 'Missouri State',
        primary: '#5E0009',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    MONMOUTH: {
        displayName: 'Monmouth',
        primary: '#002D56',
        secondary: '#B2B2B2',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MONTANA: {
        displayName: 'Montana',
        primary: '#630031',
        secondary: '#999999',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MONTANA_STATE: {
        displayName: 'Montana State',
        primary: '#00205B',
        secondary: '#B9975B',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MOREHEAD_STATE: {
        displayName: 'Morehead State',
        primary: '#005EB8',
        secondary: '#FFCF00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MORGAN_STATE: {
        displayName: 'Morgan State',
        primary: '#1B4383',
        secondary: '#F47937',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MT_ST_MARYS: {
        displayName: 'Mount St. Mary\'s',
        primary: '#002855',
        secondary: '#84754E',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MURRAY_STATE: {
        displayName: 'Murray State',
        primary: '#002144',
        secondary: '#ECAC00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NAVY: {
        displayName: 'Navy',
        primary: '#00205B',
        secondary: '#C5B783',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NC_STATE: {
        displayName: 'NC State',
        primary: '#CC0000',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    NCATU: {
        displayName: 'North Carolina A&T',
        primary: '#003D6D',
        secondary: '#F3B237',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NDSU: {
        displayName: 'North Dakota State',
        primary: '#0A5640',
        secondary: '#FFC72A',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NEBRASKA: {
        displayName: 'Nebraska',
        primary: '#D00000',
        secondary: '#F5F1E7',
        accent: '#C7C8CA',
        headerText: '#FFFFFF',
        logo: null,
    },
    NEVADA: {
        displayName: 'Nevada',
        primary: '#041E42',
        secondary: '#8A8D8F',
        accent: '#231F20',
        headerText: '#FFFFFF',
        logo: null,
    },
    NEW_HAMPSHIRE: {
        displayName: 'New Hampshire',
        primary: '#041e42',
        secondary: '#BBBCBC',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NEW_MEXICO: {
        displayName: 'New Mexico',
        primary: '#BA0C2F',
        secondary: '#63666A',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NEW_MEXICO_STATE: {
        displayName: 'New Mexico State',
        primary: '#861F41',
        secondary: '#000000',
        accent: '#97999B',
        headerText: '#FFFFFF',
        logo: null,
    },
    NEW_ORLEANS: {
        displayName: 'New Orleans',
        primary: '#005CA6',
        secondary: '#A3A9AC',
        accent: '#002F56',
        headerText: '#FFFFFF',
        logo: null,
    },
    NIAGARA: {
        displayName: 'Niagara',
        primary: '#582C83',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    NICHOLLS: {
        displayName: 'Nicholls',
        primary: '#AE132A',
        secondary: '#72808A',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    NIU: {
        displayName: 'Northern Illinois',
        primary: '#BA0C2F',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NKU: {
        displayName: 'Northern Kentucky',
        primary: '#000000',
        secondary: '#FFC72C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NORFOLK_STATE: {
        displayName: 'Norfolk State',
        primary: '#007A53',
        secondary: '#F3D03E',
        accent: '#54585A',
        headerText: '#FFFFFF',
        logo: null,
    },
    NORTH_CAROLINA: {
        displayName: 'North Carolina',
        primary: '#7BAFD4',
        secondary: '#FFFFFF',
        accent: '#13294B',
        headerText: '#13294B',
        logo: null,
    },
    NORTH_DAKOTA: {
        displayName: 'North Dakota',
        primary: '#009A44',
        secondary: '#AAAEAD',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    NORTH_FLORIDA: {
        displayName: 'North Florida',
        primary: '#002447',
        secondary: '#A5ACAF',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NORTH_TEXAS: {
        displayName: 'North Texas',
        primary: '#00853E',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    NORTHERN_ARIZONA: {
        displayName: 'Northern Arizona',
        primary: '#003466',
        secondary: '#FFD200',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NORTHERN_IOWA: {
        displayName: 'Northern Iowa',
        primary: '#4B116F',
        secondary: '#FFCC00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NORTHWESTERN: {
        displayName: 'Northwestern',
        primary: '#4E2A84',
        secondary: '#FFFFFF',
        accent: '#B6ACD1',
        headerText: '#FFFFFF',
        logo: null,
    },
    NORTHWESTERN_STATE: {
        displayName: 'Northwestern State',
        primary: '#663399',
        secondary: '#FF6600',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NOTRE_DAME: {
        displayName: 'Notre Dame',
        primary: '#0C2340',
        secondary: '#C99700',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    OAKLAND: {
        displayName: 'Oakland',
        primary: '#B59A57',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    OHIO: {
        displayName: 'Ohio',
        primary: '#00694E',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    OHIO_STATE: {
        displayName: 'Ohio State',
        primary: '#BB0000',
        secondary: '#666666',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    OKLAHOMA: {
        displayName: 'Oklahoma',
        primary: '#841617',
        secondary: '#FDF9D8',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    OKLAHOMA_STATE: {
        displayName: 'Oklahoma State',
        primary: '#FF7300',
        secondary: '#000000',
        accent: '#231F20',
        headerText: '#000000',
        logo: null,
    },
    OLD_DOMINION: {
        displayName: 'Old Dominion',
        primary: '#003057',
        secondary: '#7C878E',
        accent: '#0084A9',
        headerText: '#FFFFFF',
        logo: null,
    },
    OLE_MISS: {
        displayName: 'Ole Miss',
        primary: '#CE1126',
        secondary: '#14213D',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    ORAL_ROBERTS: {
        displayName: 'Oral Roberts',
        primary: '#002F60',
        secondary: '#C5B783',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    OREGON: {
        displayName: 'Oregon',
        primary: '#154733',
        secondary: '#FEE123',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    OREGON_STATE: {
        displayName: 'Oregon State',
        primary: '#D73F09',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    PACIFIC: {
        displayName: 'Pacific',
        primary: '#FF671D',
        secondary: '#0F0F0F',
        accent: '#F4B223',
        headerText: '#FFFFFF',
        logo: null,
    },
    PENN: {
        displayName: 'Penn',
        primary: '#990000',
        secondary: '#011F5B',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    PENN_STATE: {
        displayName: 'Penn State',
        primary: '#041E42',
        secondary: '#FFFFFF',
        accent: '#A2AAAD',
        headerText: '#FFFFFF',
        logo: null,
    },
    PEPPERDINE: {
        displayName: 'Pepperdine',
        primary: '#00205c',
        secondary: '#c25700',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    PITT: {
        displayName: 'Pitt',
        primary: '#003594',
        secondary: '#FFB81C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    PORTLAND: {
        displayName: 'Portland',
        primary: '#1E1656',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    PORTLAND_STATE: {
        displayName: 'Portland State',
        primary: '#154734',
        secondary: '#FFFFFF',
        accent: '#A5ACAF',
        headerText: '#FFFFFF',
        logo: null,
    },
    PRINCETON: {
        displayName: 'Princeton',
        primary: '#FF671F',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    PROVIDENCE: {
        displayName: 'Providence',
        primary: '#000000',
        secondary: '#8A8D8F',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    PURDUE: {
        displayName: 'Purdue',
        primary: '#000000',
        secondary: '#CFB991',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    RADFORD: {
        displayName: 'Radford',
        primary: '#C2011B',
        secondary: '#D1D3D4',
        accent: '#003C71',
        headerText: '#FFFFFF',
        logo: null,
    },
    RHODE_ISLAND: {
        displayName: 'Rhode Island',
        primary: '#002147',
        secondary: '#68ABE8',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    RICE: {
        displayName: 'Rice',
        primary: '#00205B',
        secondary: '#C1C6C8',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    RICHMOND: {
        displayName: 'Richmond',
        primary: '#000066',
        secondary: '#990000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    ROBERT_MORRIS: {
        displayName: 'Robert Morris',
        primary: '#14234B',
        secondary: '#A6192E',
        accent: '#B2B1AE',
        headerText: '#FFFFFF',
        logo: null,
    },
    RUTGERS: {
        displayName: 'Rutgers',
        primary: '#CC0033',
        secondary: '#5F6A72',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    SACRAMENTO_STATE: {
        displayName: 'Sacramento State',
        primary: '#043927',
        secondary: '#C4B581',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    SAINT_FRANCIS: {
        displayName: 'Saint Francis',
        primary: '#BD1F25',
        secondary: '#000000',
        accent: '#8E908F',
        headerText: '#FFFFFF',
        logo: null,
    },
    SAINT_JOSEPHS: {
        displayName: 'Saint Joseph\'s',
        primary: '#9E1B32',
        secondary: '#6C6F70',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    SAINT_LOUIS: {
        displayName: 'Saint Louis',
        primary: '#003DA5',
        secondary: '#FFFFFF',
        accent: '#C8C9C7',
        headerText: '#FFFFFF',
        logo: null,
    },
    SAINT_MARYS: {
        displayName: 'Saint Mary\'s',
        primary: '#143257',
        secondary: '#D82732',
        accent: '#81959B',
        headerText: '#FFFFFF',
        logo: null,
    },
    SAM_HOUSTON: {
        displayName: 'Sam Houston',
        primary: '#FE5100',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    SAMFORD: {
        displayName: 'Samford',
        primary: '#002649',
        secondary: '#C4161D',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    SAN_DIEGO: {
        displayName: 'San Diego',
        primary: '#003B70',
        secondary: '#75BEE9',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    SAN_DIEGO_STATE: {
        displayName: 'San Diego State',
        primary: '#A6192E',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    SAN_FRANCISCO: {
        displayName: 'San Francisco',
        primary: '#00543C',
        secondary: '#FDBB30',
        accent: '#919194',
        headerText: '#FFFFFF',
        logo: null,
    },
    SAN_JOSE_STATE: {
        displayName: 'San Jose State',
        primary: '#0055A2',
        secondary: '#E5A823',
        accent: '#939597',
        headerText: '#FFFFFF',
        logo: null,
    },
    SANTA_CLARA: {
        displayName: 'Santa Clara',
        primary: '#862633',
        secondary: '#FFFFFF',
        accent: '#758592',
        headerText: '#FFFFFF',
        logo: null,
    },
    SDSU: {
        displayName: 'South Dakota State',
        primary: '#0033A0',
        secondary: '#FFD100',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    SE_LOUISIANA: {
        displayName: 'SE Louisiana',
        primary: '#006341',
        secondary: '#EAAA00',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    SEATTLE: {
        displayName: 'Seattle',
        primary: '#AA0000',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    SEMO: {
        displayName: 'SEMO',
        primary: '#C8102E',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    SETON_HALL: {
        displayName: 'Seton Hall',
        primary: '#003A70',
        secondary: '#A7A8AA',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    SIENA: {
        displayName: 'Siena',
        primary: '#006747',
        secondary: '#FFC72C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    SMU: {
        displayName: 'SMU',
        primary: '#354Ca1',
        secondary: '#CC0035',
        accent: '#262626',
        headerText: '#FFFFFF',
        logo: null,
    },
    SOUTH_ALABAMA: {
        displayName: 'South Alabama',
        primary: '#BF0D3E',
        secondary: '#00205B',
        accent: '#A2AAAD',
        headerText: '#FFFFFF',
        logo: null,
    },
    SOUTH_CAROLINA: {
        displayName: 'South Carolina',
        primary: '#73000A',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    SOUTH_FLORIDA: {
        displayName: 'South Florida',
        primary: '#006747',
        secondary: '#CFC493',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    SOUTHERN: {
        displayName: 'Southern',
        primary: '#58B6E7',
        secondary: '#FFCE34',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    SOUTHERN_ILLINOIS: {
        displayName: 'Southern Illinois',
        primary: '#720000',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    SOUTHERN_MISS: {
        displayName: 'Southern Miss',
        primary: '#FFAB00',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#000000',
        logo: null,
    },
    SOUTHERN_UTAH: {
        displayName: 'Southern Utah',
        primary: '#C41425',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    ST_BONAVENTURE: {
        displayName: 'St. Bonaventure',
        primary: '#54261A',
        secondary: '#BDB6B0',
        accent: '#FDB726',
        headerText: '#FFFFFF',
        logo: null,
    },
    ST_FRANCIS_COLLEGE: {
        displayName: 'St. Francis College',
        primary: '#004C97',
        secondary: '#E03A3E',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    ST_JOHNS: {
        displayName: "St. John's",
        primary: '#BA0C2F',
        secondary: '#041C2C',
        accent: '#808285',
        headerText: '#FFFFFF',
        logo: null,
    },
    ST_PETERS: {
        displayName: "St. Peter's",
        primary: '#003C71',
        secondary: '#A59C94',
        accent: '#0072CE',
        headerText: '#FFFFFF',
        logo: null,
    },
    STANFORD: {
        displayName: 'Stanford',
        primary: '#8C1515',
        secondary: '#FFFFFF',
        accent: '#53565A',
        headerText: '#FFFFFF',
        logo: null,
    },
    STEPHEN_F_AUSTIN: {
        displayName: 'Stephen F. Austin',
        primary: '#613393',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    STETSON: {
        displayName: 'Stetson',
        primary: '#00523E',
        secondary: '#FFFFFF',
        accent: '#86898C',
        headerText: '#FFFFFF',
        logo: null,
    },
    STONY_BROOK: {
        displayName: 'Stony Brook',
        primary: '#16243E',
        secondary: '#990000',
        accent: '#828282',
        headerText: '#FFFFFF',
        logo: null,
    },
    SYRACUSE: {
        displayName: 'Syracuse',
        primary: '#D44500',
        secondary: '#0C2340',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    TARLETON_STATE: {
        displayName: 'Tarleton State',
        primary: '#4F2D7F',
        secondary: '#FFFFFF',
        accent: '#6D6E71',
        headerText: '#FFFFFF',
        logo: null,
    },
    TCU: {
        displayName: 'TCU',
        primary: '#4D1979',
        secondary: '#FFFFFF',
        accent: '#A3A9AC',
        headerText: '#FFFFFF',
        logo: null,
    },
    TEMPLE: {
        displayName: 'Temple',
        primary: '#9D2235',
        secondary: '#FFFFFF',
        accent: '#8A8D8F',
        headerText: '#FFFFFF',
        logo: null,
    },
    TENNESSEE: {
        displayName: 'Tennessee',
        primary: '#FF8200',
        secondary: '#FFFFFF',
        accent: '#58595B',
        headerText: '#FFFFFF',
        logo: null,
    },
    TENNESSEE_TECH: {
        displayName: 'Tennessee Tech',
        primary: '#4F2984',
        secondary: '#FFDD00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    TEXAS: {
        displayName: 'Texas',
        primary: '#BF5700',
        secondary: '#FFFFFF',
        accent: '#333F48',
        headerText: '#FFFFFF',
        logo: null,
    },
    TEXAS_AM: {
        displayName: 'Texas A&M',
        primary: '#500000',
        secondary: '#FFFFFF',
        accent: '#332C2C',
        headerText: '#FFFFFF',
        logo: null,
    },
    TEXAS_AM_CC: {
        displayName: 'Texas A&M-CC',
        primary: '#0067C5',
        secondary: '#007F3E',
        accent: '#9EA2A4',
        headerText: '#FFFFFF',
        logo: null,
    },
    TEXAS_SOUTHERN: {
        displayName: 'Texas Southern',
        primary: '#7C183E',
        secondary: '#9DA6AB',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    TEXAS_STATE: {
        displayName: 'Texas State',
        primary: '#501214',
        secondary: '#AC9155',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    TEXAS_TECH: {
        displayName: 'Texas Tech',
        primary: '#CC0000',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    THE_CITADEL: {
        displayName: 'The Citadel',
        primary: '#3975B7',
        secondary: '#1F3A60',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    TOLEDO: {
        displayName: 'Toledo',
        primary: '#15397F',
        secondary: '#FFDA00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    TOWSON: {
        displayName: 'Towson',
        primary: '#FFBB00',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    TROY: {
        displayName: 'Troy',
        primary: '#8A2432',
        secondary: '#B3B5B8',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    TULANE: {
        displayName: 'Tulane',
        primary: '#006747',
        secondary: '#418FDE',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    TULSA: {
        displayName: 'Tulsa',
        primary: '#D0B787',
        secondary: '#003595',
        accent: '#CE0E2D',
        headerText: '#FFFFFF',
        logo: null,
    },
    UAB: {
        displayName: 'UAB',
        primary: '#006341',
        secondary: '#CC8A00',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    UC_DAVIS: {
        displayName: 'UC Davis',
        primary: '#002855',
        secondary: '#B3A369',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    UC_IRVINE: {
        displayName: 'UC Irvine',
        primary: '#0C2340',
        secondary: '#FFD200',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    UC_RIVERSIDE: {
        displayName: 'UC Riverside',
        primary: '#003066',
        secondary: '#F1AB00',
        accent: '#2D6CC0',
        headerText: '#FFFFFF',
        logo: null,
    },
    UCF: {
        displayName: 'UCF',
        primary: '#BA9B37',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#000000',
        logo: null,
    },
    UCLA: {
        displayName: 'UCLA',
        primary: '#2774AE',
        secondary: '#FFD100',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    UCONN: {
        displayName: 'UConn',
        primary: '#000E2F',
        secondary: '#FFFFFF',
        accent: '#E4002B',
        headerText: '#FFFFFF',
        logo: null,
    },
    UCSB: {
        displayName: 'UCSB',
        primary: '#003660',
        secondary: '#FEBC11',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    UIC: {
        displayName: 'UIC',
        primary: '#AC1E2D',
        secondary: '#041E42',
        accent: '#FACC09',
        headerText: '#FFFFFF',
        logo: null,
    },
    UL_LAFAYETTE: {
        displayName: 'UL Lafayette',
        primary: '#CE181E',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    UL_MONROE: {
        displayName: 'UL Monroe',
        primary: '#840029',
        secondary: '#FDB913',
        accent: '#646469',
        headerText: '#FFFFFF',
        logo: null,
    },
    UMASS: {
        displayName: 'UMass',
        primary: '#881240',
        secondary: '#000000',
        accent: '#A2AAAD',
        headerText: '#FFFFFF',
        logo: null,
    },
    UMASS_LOWELL: {
        displayName: 'UMass Lowell',
        primary: '#0067B1',
        secondary: '#C8102E',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    UMBC: {
        displayName: 'UMBC',
        primary: '#000000',
        secondary: '#FFC20E',
        accent: '#E0121A',
        headerText: '#FFFFFF',
        logo: null,
    },
    UMES: {
        displayName: 'UMES',
        primary: '#862633',
        secondary: '#888B8D',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    UMKC: {
        displayName: 'UMKC',
        primary: '#005293',
        secondary: '#FECB00',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    UNC_ASHEVILLE: {
        displayName: 'UNC Asheville',
        primary: '#003DA5',
        secondary: '#FFFFFF',
        accent: '#808285',
        headerText: '#FFFFFF',
        logo: null,
    },
    UNCG: {
        displayName: 'UNCG',
        primary: '#0F2044',
        secondary: '#FFB71B',
        accent: '#BEC0C2',
        headerText: '#FFFFFF',
        logo: null,
    },
    UNCW: {
        displayName: 'UNCW',
        primary: '#006666',
        secondary: '#003366',
        accent: '#FFD600',
        headerText: '#FFFFFF',
        logo: null,
    },
    UNLV: {
        displayName: 'UNLV',
        primary: '#CF0A2C',
        secondary: '#000000',
        accent: '#8D9093',
        headerText: '#FFFFFF',
        logo: null,
    },
    USC: {
        displayName: 'USC',
        primary: '#990000',
        secondary: '#FFCC00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    USC_UPSTATE: {
        displayName: 'USC Upstate',
        primary: '#00703C',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    UT_MARTIN: {
        displayName: 'UT Martin',
        primary: '#F79728',
        secondary: '#002A5B',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    UTAH: {
        displayName: 'Utah',
        primary: '#CC0000',
        secondary: '#000000',
        accent: '#2F2F2F',
        headerText: '#FFFFFF',
        logo: null,
    },
    UTAH_STATE: {
        displayName: 'Utah State',
        primary: '#0F2439',
        secondary: '#FFFFFF',
        accent: '#A7A8AA',
        headerText: '#FFFFFF',
        logo: null,
    },
    UTAH_VALLEY: {
        displayName: 'Utah Valley',
        primary: '#275D38',
        secondary: '#000000',
        accent: '#8E8C89',
        headerText: '#FFFFFF',
        logo: null,
    },
    UTEP: {
        displayName: 'UTEP',
        primary: '#FF8200',
        secondary: '#041E42',
        accent: '#B1B3B3',
        headerText: '#FFFFFF',
        logo: null,
    },
    UTSA: {
        displayName: 'UTSA',
        primary: '#0C2340',
        secondary: '#F15A22',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    UWMILWAUKEE: {
        displayName: 'Milwaukee',
        primary: '#000000',
        secondary: '#FFBD00',
        accent: '#CCCCCC',
        headerText: '#FFFFFF',
        logo: null,
    },
    VALPARAISO: {
        displayName: 'Valparaiso',
        primary: '#381E0E',
        secondary: '#FFCC00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    VANDERBILT: {
        displayName: 'Vanderbilt',
        primary: '#000000',
        secondary: '#866D4B',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    VCU: {
        displayName: 'VCU',
        primary: '#FFB300',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    VERMONT: {
        displayName: 'Vermont',
        primary: '#004C36',
        secondary: '#FFC72C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    VILLANOVA: {
        displayName: 'Villanova',
        primary: '#00205B',
        secondary: '#13B5EA',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    VIRGINIA: {
        displayName: 'Virginia',
        primary: '#232D4B',
        secondary: '#F84C1E',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    VIRGINIA_TECH: {
        displayName: 'Virginia Tech',
        primary: '#630031',
        secondary: '#CF4420',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    VMI: {
        displayName: 'VMI',
        primary: '#A31236',
        secondary: '#FFB300',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WAGNER: {
        displayName: 'Wagner',
        primary: '#00483A',
        secondary: '#FFFFFF',
        accent: '#B9BBBD',
        headerText: '#FFFFFF',
        logo: null,
    },
    WAKE_FOREST: {
        displayName: 'Wake Forest',
        primary: '#000000',
        secondary: '#9E7E38',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WASHINGTON: {
        displayName: 'Washington',
        primary: '#4B2E83',
        secondary: '#B7A57A',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WASHINGTON_STATE: {
        displayName: 'Washington State',
        primary: '#A60F2D',
        secondary: '#4D4D4D',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WEBER_STATE: {
        displayName: 'Weber State',
        primary: '#4B2682',
        secondary: '#A1A1A4',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WEST_VIRGINIA: {
        displayName: 'West Virginia',
        primary: '#002855',
        secondary: '#EAAA00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WESTERN_CAROLINA: {
        displayName: 'Western Carolina',
        primary: '#592C88',
        secondary: '#C1A875',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WESTERN_ILLINOIS: {
        displayName: 'Western Illinois',
        primary: '#663399',
        secondary: '#FFCC00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WESTERN_MICHIGAN: {
        displayName: 'Western Michigan',
        primary: '#634923',
        secondary: '#B5985A',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    WICHITA_STATE: {
        displayName: 'Wichita State',
        primary: '#000000',
        secondary: '#FFDB00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WILLIAM_MARY: {
        displayName: 'William & Mary',
        primary: '#115740',
        secondary: '#F0B323',
        accent: '#D8DCDB',
        headerText: '#FFFFFF',
        logo: null,
    },
    WINTHROP: {
        displayName: 'Winthrop',
        primary: '#660000',
        secondary: '#F0B323',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WISCONSIN: {
        displayName: 'Wisconsin',
        primary: '#C5050C',
        secondary: '#FFFFFF',
        accent: '#9B9B9B',
        headerText: '#FFFFFF',
        logo: null,
    },
    WKU: {
        displayName: 'Western Kentucky',
        primary: '#C60C30',
        secondary: '#000000',
        accent: '#A2A4A3',
        headerText: '#FFFFFF',
        logo: null,
    },
    WOFFORD: {
        displayName: 'Wofford',
        primary: '#886E4C',
        secondary: '#000000',
        accent: '#C7B37F',
        headerText: '#FFFFFF',
        logo: null,
    },
    WRIGHT_STATE: {
        displayName: 'Wright State',
        primary: '#004035',
        secondary: '#B29D6C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WYOMING: {
        displayName: 'Wyoming',
        primary: '#492F24',
        secondary: '#FFC425',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    XAVIER: {
        displayName: 'Xavier',
        primary: '#0C2340',
        secondary: '#9EA2A2',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    YALE: {
        displayName: 'Yale',
        primary: '#00356B',
        secondary: '#FFFFFF',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    YOUNGSTOWN_STATE: {
        displayName: 'Youngstown State',
        primary: '#D21034',
        secondary: '#FFFFFF',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
};

const FALLBACK_BRANDING: TeamBranding = {
    displayName: 'Team',
    primary: '#111111',
    secondary: '#FFFFFF',
    accent: '#D0D0D0',
    headerText: '#FFFFFF',
    logo: null,
};

export function getTeamBranding(teamId?: string | null): TeamBranding {
    if (!teamId) return FALLBACK_BRANDING;

    const normalized = String(teamId).trim().toUpperCase();
    const base =
        TEAM_BRANDING[normalized] ?? {
            ...FALLBACK_BRANDING,
            displayName: normalized.replace(/_/g, ' '),
        };

    return {
        ...base,
        logo: getTeamLogo(normalized),
    };
}