import { getTeamLogo } from '@/lib/teamLogos';

export type TeamBranding = {
    displayName: string;
    primary: string;
    secondary: string;
    accent: string;
    headerText: string;
    logo: any | null;
};

const TEAM_BRANDING: Record<string, TeamBranding> = {
    ALABAMA: {
        displayName: 'Alabama',
        primary: '#9E1B32',
        secondary: '#FFFFFF',
        accent: '#828A8F',
        headerText: '#FFFFFF',
        logo: null,
    },
    ARIZONA: {
        displayName: 'Arizona',
        primary: '#003366',
        secondary: '#CC0033',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    ARIZONA_STATE: {
        displayName: 'Arizona State',
        primary: '#8C1D40',
        secondary: '#FFC627',
        accent: '#1E1E1E',
        headerText: '#FFFFFF',
        logo: null,
    },
    AUBURN: {
        displayName: 'Auburn',
        primary: '#0C2340',
        secondary: '#E87722',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    BAYLOR: {
        displayName: 'Baylor',
        primary: '#154734',
        secondary: '#FFB81C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    BOISE_STATE: {
        displayName: 'Boise State',
        primary: '#0033A0',
        secondary: '#D64309',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    BYU: {
        displayName: 'BYU',
        primary: '#002E5D',
        secondary: '#FFFFFF',
        accent: '#6CACE4',
        headerText: '#FFFFFF',
        logo: null,
    },
    CAL: {
        displayName: 'Cal',
        primary: '#003262',
        secondary: '#FDB515',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    CINCINNATI: {
        displayName: 'Cincinnati',
        primary: '#E00122',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    CLEMSON: {
        displayName: 'Clemson',
        primary: '#F56600',
        secondary: '#522D80',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    COLORADO: {
        displayName: 'Colorado',
        primary: '#000000',
        secondary: '#CFB87C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    CREIGHTON: {
        displayName: 'Creighton',
        primary: '#005CA9',
        secondary: '#FFFFFF',
        accent: '#041E42',
        headerText: '#FFFFFF',
        logo: null,
    },
    DUKE: {
        displayName: 'Duke',
        primary: '#003087',
        secondary: '#FFFFFF',
        accent: '#012169',
        headerText: '#FFFFFF',
        logo: null,
    },
    FLORIDA: {
        displayName: 'Florida',
        primary: '#0021A5',
        secondary: '#FA4616',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    FLORIDA_STATE: {
        displayName: 'Florida State',
        primary: '#782F40',
        secondary: '#CEB888',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    GEORGETOWN: {
        displayName: 'Georgetown',
        primary: '#041E42',
        secondary: '#9EA2A2',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    GONZAGA: {
        displayName: 'Gonzaga',
        primary: '#041E42',
        secondary: '#C8102E',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    HOUSTON: {
        displayName: 'Houston',
        primary: '#C8102E',
        secondary: '#FFFFFF',
        accent: '#231F20',
        headerText: '#FFFFFF',
        logo: null,
    },
    INDIANA: {
        displayName: 'Indiana',
        primary: '#990000',
        secondary: '#EEEDEB',
        accent: '#231F20',
        headerText: '#FFFFFF',
        logo: null,
    },
    IOWA: {
        displayName: 'Iowa',
        primary: '#000000',
        secondary: '#FFCD00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    IOWA_STATE: {
        displayName: 'Iowa State',
        primary: '#C8102E',
        secondary: '#F1BE48',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    KANSAS: {
        displayName: 'Kansas',
        primary: '#0051BA',
        secondary: '#E8000D',
        accent: '#FFC82D',
        headerText: '#FFFFFF',
        logo: null,
    },
    KANSAS_STATE: {
        displayName: 'Kansas State',
        primary: '#512888',
        secondary: '#FFFFFF',
        accent: '#D1D3D4',
        headerText: '#FFFFFF',
        logo: null,
    },
    KENTUCKY: {
        displayName: 'Kentucky',
        primary: '#0033A0',
        secondary: '#FFFFFF',
        accent: '#C4CED4',
        headerText: '#FFFFFF',
        logo: null,
    },
    LOUISVILLE: {
        displayName: 'Louisville',
        primary: '#AD0000',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    LSU: {
        displayName: 'LSU',
        primary: '#461D7C',
        secondary: '#FDD023',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MARQUETTE: {
        displayName: 'Marquette',
        primary: '#003366',
        secondary: '#FFB81C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MARYLAND: {
        displayName: 'Maryland',
        primary: '#E03A3E',
        secondary: '#FFD520',
        accent: '#000000',
        headerText: '#FFFFFF',
        logo: null,
    },
    MEMPHIS: {
        displayName: 'Memphis',
        primary: '#003087',
        secondary: '#9EA2A2',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    MICHIGAN: {
        displayName: 'Michigan',
        primary: '#00274C',
        secondary: '#FFCB05',
        accent: '#1D1D1D',
        headerText: '#FFFFFF',
        logo: null,
    },
    MICHIGAN_STATE: {
        displayName: 'Michigan State',
        primary: '#18453B',
        secondary: '#FFFFFF',
        accent: '#B2B4B2',
        headerText: '#FFFFFF',
        logo: null,
    },
    MISSOURI: {
        displayName: 'Missouri',
        primary: '#000000',
        secondary: '#F1B82D',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NEW_MEXICO: {
        displayName: 'New Mexico',
        primary: '#BA0C2F',
        secondary: '#63666A',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    NORTH_CAROLINA: {
        displayName: 'North Carolina',
        primary: '#7BAFD4',
        secondary: '#FFFFFF',
        accent: '#13294B',
        headerText: '#13294B',
        logo: null,
    },
    NORTHWESTERN: {
        displayName: 'Northwestern',
        primary: '#4E2A84',
        secondary: '#FFFFFF',
        accent: '#B6ACD1',
        headerText: '#FFFFFF',
        logo: null,
    },
    NOTRE_DAME: {
        displayName: 'Notre Dame',
        primary: '#0C2340',
        secondary: '#C99700',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    OHIO_STATE: {
        displayName: 'Ohio State',
        primary: '#BB0000',
        secondary: '#666666',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    OKLAHOMA: {
        displayName: 'Oklahoma',
        primary: '#841617',
        secondary: '#FDF9D8',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    OKLAHOMA_STATE: {
        displayName: 'Oklahoma State',
        primary: '#FF7300',
        secondary: '#000000',
        accent: '#231F20',
        headerText: '#000000',
        logo: null,
    },
    OLE_MISS: {
        displayName: 'Ole Miss',
        primary: '#CE1126',
        secondary: '#14213D',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    OREGON: {
        displayName: 'Oregon',
        primary: '#154733',
        secondary: '#FEE123',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    PENN_STATE: {
        displayName: 'Penn State',
        primary: '#041E42',
        secondary: '#FFFFFF',
        accent: '#A2AAAD',
        headerText: '#FFFFFF',
        logo: null,
    },
    PITT: {
        displayName: 'Pitt',
        primary: '#003594',
        secondary: '#FFB81C',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    PROVIDENCE: {
        displayName: 'Providence',
        primary: '#000000',
        secondary: '#8A8D8F',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    PURDUE: {
        displayName: 'Purdue',
        primary: '#000000',
        secondary: '#CFB991',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    RUTGERS: {
        displayName: 'Rutgers',
        primary: '#CC0033',
        secondary: '#5F6A72',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    SAN_DIEGO_STATE: {
        displayName: 'San Diego State',
        primary: '#A6192E',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    SETON_HALL: {
        displayName: 'Seton Hall',
        primary: '#003A70',
        secondary: '#A7A8AA',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    ST_JOHNS: {
        displayName: "St. John's",
        primary: '#BA0C2F',
        secondary: '#041C2C',
        accent: '#808285',
        headerText: '#FFFFFF',
        logo: null,
    },
    SYRACUSE: {
        displayName: 'Syracuse',
        primary: '#D44500',
        secondary: '#0C2340',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    TEMPLE: {
        displayName: 'Temple',
        primary: '#9D2235',
        secondary: '#FFFFFF',
        accent: '#8A8D8F',
        headerText: '#FFFFFF',
        logo: null,
    },
    TENNESSEE: {
        displayName: 'Tennessee',
        primary: '#FF8200',
        secondary: '#FFFFFF',
        accent: '#58595B',
        headerText: '#FFFFFF',
        logo: null,
    },
    TEXAS: {
        displayName: 'Texas',
        primary: '#BF5700',
        secondary: '#FFFFFF',
        accent: '#333F48',
        headerText: '#FFFFFF',
        logo: null,
    },
    TEXAS_AM: {
        displayName: 'Texas A&M',
        primary: '#500000',
        secondary: '#FFFFFF',
        accent: '#332C2C',
        headerText: '#FFFFFF',
        logo: null,
    },
    TEXAS_TECH: {
        displayName: 'Texas Tech',
        primary: '#CC0000',
        secondary: '#000000',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    UCLA: {
        displayName: 'UCLA',
        primary: '#2774AE',
        secondary: '#FFD100',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    UCONN: {
        displayName: 'UConn',
        primary: '#000E2F',
        secondary: '#FFFFFF',
        accent: '#E4002B',
        headerText: '#FFFFFF',
        logo: null,
    },
    UNLV: {
        displayName: 'UNLV',
        primary: '#CF0A2C',
        secondary: '#000000',
        accent: '#8D9093',
        headerText: '#FFFFFF',
        logo: null,
    },
    USC: {
        displayName: 'USC',
        primary: '#990000',
        secondary: '#FFCC00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    UTAH_STATE: {
        displayName: 'Utah State',
        primary: '#0F2439',
        secondary: '#FFFFFF',
        accent: '#A7A8AA',
        headerText: '#FFFFFF',
        logo: null,
    },
    VANDERBILT: {
        displayName: 'Vanderbilt',
        primary: '#000000',
        secondary: '#866D4B',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    VILLANOVA: {
        displayName: 'Villanova',
        primary: '#00205B',
        secondary: '#13B5EA',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    VIRGINIA: {
        displayName: 'Virginia',
        primary: '#232D4B',
        secondary: '#F84C1E',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    VIRGINIA_TECH: {
        displayName: 'Virginia Tech',
        primary: '#630031',
        secondary: '#CF4420',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WAKE_FOREST: {
        displayName: 'Wake Forest',
        primary: '#000000',
        secondary: '#9E7E38',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WASHINGTON: {
        displayName: 'Washington',
        primary: '#4B2E83',
        secondary: '#B7A57A',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WEST_VIRGINIA: {
        displayName: 'West Virginia',
        primary: '#002855',
        secondary: '#EAAA00',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
    WISCONSIN: {
        displayName: 'Wisconsin',
        primary: '#C5050C',
        secondary: '#FFFFFF',
        accent: '#9B9B9B',
        headerText: '#FFFFFF',
        logo: null,
    },
    XAVIER: {
        displayName: 'Xavier',
        primary: '#0C2340',
        secondary: '#9EA2A2',
        accent: '#FFFFFF',
        headerText: '#FFFFFF',
        logo: null,
    },
};

const FALLBACK_BRANDING: TeamBranding = {
    displayName: 'Team',
    primary: '#111111',
    secondary: '#FFFFFF',
    accent: '#D0D0D0',
    headerText: '#FFFFFF',
    logo: null,
};

export function getTeamBranding(teamId?: string | null): TeamBranding {
    if (!teamId) return FALLBACK_BRANDING;

    const normalized = String(teamId).trim().toUpperCase();
    const base =
        TEAM_BRANDING[normalized] ?? {
            ...FALLBACK_BRANDING,
            displayName: normalized.replace(/_/g, ' '),
        };

    return {
        ...base,
        logo: getTeamLogo(normalized),
    };
}